version: '2'

services:

  head:
    container_name: head
    build: ./dockermaze2-head
    environment:
    - DM2_ENDPOINT=backend.public.schibsted.io
    ports:
    - "7777:7777"
    - "80:80"
    env_file:
    - token.env

  legs:
    container_name: legs
    build: ./dockermaze2-legs-game
    links:
    - head

  arms:
    container_name: arms
    build: ./dockermaze2-arms-game
    depends_on:
    - head
    - stockfish

  weapon:
    container_name: weapon
    build: ./dockermaze2-weapon-game
    depends_on:
    - head

  stockfish:
    container_name: stockfish
    build: ./dockermaze2-stockfish
    ports:
    - "9999:9999"

  radio:
    container_name: radio
    build: ./dockermaze2-radio-game
    links:
    - head:head

  heart:
    container_name: heart
    build: ./dockermaze2-heart-game
    depends_on:
    - head
